"""Agentic Tactics Copilot — Streamlit UI."""

from __future__ import annotations

import json
from pathlib import Path

import streamlit as st

from app.config import REPORTS_DIR, ProviderConfig, get_providers
from rag.pipeline import run_query

st.set_page_config(page_title="Tactics Copilot", page_icon="🛡️", layout="wide")


# ── helper functions (must be defined before use) ────────────────────────────


def _render_parsed_answer(parsed: dict, result: dict) -> None:
    """Display structured answer and sources."""
    answer_mode = parsed.get("mode", "unknown")

    if answer_mode == "recommend":
        st.markdown(f"**Summary:** {parsed.get('summary', '')}")
        for t in parsed.get("tactics", []):
            with st.expander(f"✅ {t.get('tactic_name', 'Tactic')} ({t.get('category', '')})"):
                st.markdown(f"**Type:** {t.get('tactic_type', '')}")
                st.markdown(f"**Description:** {t.get('description', '')}")
                st.markdown(f"**Source:** {t.get('source', '')}")
                if t.get("source_doi"):
                    st.markdown(f"**DOI:** {t['source_doi']}")
        if parsed.get("dark_tactic_risks"):
            st.warning("**Dark Tactic Risks:** " + "; ".join(parsed["dark_tactic_risks"]))
        if parsed.get("next_steps"):
            st.info("**Next Steps:** " + " | ".join(parsed["next_steps"]))

    elif answer_mode == "critique":
        verdict = parsed.get("verdict_label", parsed.get("verdict", ""))
        if "dark" in str(parsed.get("verdict", "")).lower():
            st.error(f"**Verdict:** {verdict}")
        elif "mixed" in str(parsed.get("verdict", "")).lower():
            st.warning(f"**Verdict:** {verdict}")
        else:
            st.success(f"**Verdict:** {verdict}")
        st.markdown(parsed.get("analysis", ""))
        for t in parsed.get("matched_tactics", []):
            with st.expander(f"{t.get('tactic_name', 'Tactic')} ({t.get('category', '')})"):
                st.markdown(f"**Type:** {t.get('tactic_type', '')}")
                st.markdown(f"**Description:** {t.get('description', '')}")
        if parsed.get("alternatives"):
            st.info("**Alternatives:** " + " | ".join(parsed["alternatives"]))

    elif answer_mode == "compare":
        st.markdown(f"**Comparing:** {', '.join(parsed.get('subjects', []))}")
        table = parsed.get("comparison_table", {})
        if table:
            st.json(table)
        if parsed.get("key_tradeoffs"):
            st.markdown("**Key Trade-offs:**")
            for kv in parsed["key_tradeoffs"]:
                st.markdown(f"- {kv}")
        st.markdown(f"**Recommendation:** {parsed.get('recommendation', '')}")

    else:
        st.json(parsed)

    if parsed.get("grounding_note"):
        st.caption(parsed["grounding_note"])

    with st.expander("Retrieved Sources"):
        for src in result.get("retrieved_tactics", []):
            st.markdown(
                f"- **{src['title']}** ({src['category']}, {src['tactic_type']}) "
                f"— distance: {src['distance']:.3f}"
            )
            if src.get("url"):
                st.markdown(f"  [{src['url']}]({src['url']})")

    st.caption(f"Provider: {result.get('provider')} | Latency: {result.get('latency_seconds', 0):.1f}s")

    display_text = json.dumps(parsed, indent=2, ensure_ascii=False)
    st.session_state.chat_history.append({"role": "assistant", "content": display_text})


def _build_report_markdown(parsed: dict) -> str:
    """Generate a markdown report from agent analysis output."""
    lines = ["# Tactics Analysis Report", ""]
    lines.append("## Project Summary")
    lines.append(parsed.get("project_summary", "(no summary)"))
    lines.append("")

    lines.append("## Identified Tactics (Awesome)")
    for t in parsed.get("awesome_tactics", []):
        lines.append(
            f"- **{t.get('tactic_name', '')}** ({t.get('category', '')}): "
            f"{t.get('description', '')}"
        )
        if t.get("source"):
            lines.append(f"  - Source: {t['source']}")
    lines.append("")

    lines.append("## Identified Risks (Dark Tactics)")
    for t in parsed.get("dark_tactic_risks", []):
        if isinstance(t, dict):
            lines.append(
                f"- **{t.get('tactic_name', '')}** ({t.get('category', '')}): "
                f"{t.get('description', '')}"
            )
        else:
            lines.append(f"- {t}")
    lines.append("")

    lines.append("## Recommendations")
    for r in parsed.get("recommendations", []):
        lines.append(f"- {r}")
    lines.append("")

    lines.append("## Sources")
    lines.append(parsed.get("grounding_note", ""))
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Agentic Tactics Copilot*")
    return "\n".join(lines)


# ── sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("Tactics Copilot")
    st.caption("RAG advisor over the AADT catalog")

    providers = get_providers()
    if not providers:
        st.warning(
            "No LLM providers configured. "
            "Create a .env file from .env.example and set at least NEBULA or OPENAI keys."
        )
        manual_base = st.text_input("LLM API base URL", value="http://localhost:11434/v1")
        manual_model = st.text_input("Model name", value="llama3")
        manual_key = st.text_input("API key (optional)", value="no-key", type="password")
        if manual_base and manual_model:
            providers = [
                ProviderConfig(
                    name=f"Manual ({manual_model})",
                    api_base=manual_base,
                    model=manual_model,
                    api_key=manual_key or "no-key",
                )
            ]

    provider_names = [p.name for p in providers] if providers else []
    selected_provider_name = st.selectbox(
        "Model", provider_names, index=0 if provider_names else None
    )
    provider = next((p for p in providers if p.name == selected_provider_name), None) if providers else None

    mode = st.selectbox("Mode", ["recommend", "critique", "compare"])

    categories = [
        None,
        "cloud-computing",
        "edge-computing",
        "green-ml-enabled-systems",
        "green-software-practice",
        "resource-adaptation",
        "resource-allocation",
        "resource-monitoring",
    ]
    category_filter = st.selectbox(
        "Filter by category (optional)",
        categories,
        format_func=lambda c: "All categories" if c is None else c,
    )

    n_results = st.slider("Retrieved tactics (top-k)", 3, 15, 8)

# ── tabs ─────────────────────────────────────────────────────────────────────
tab_chat, tab_agent, tab_benchmark = st.tabs(["Chat", "Agent Tasks", "Benchmark"])

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1 — Chat
# ═══════════════════════════════════════════════════════════════════════════════
with tab_chat:
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_input = st.chat_input("Ask about software tactics...")

    if user_input and provider:
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        with st.chat_message("assistant"):
            with st.spinner("Retrieving tactics & generating answer..."):
                result = run_query(
                    user_query=user_input,
                    mode=mode,
                    provider=provider,
                    n_results=n_results,
                    category_filter=category_filter,
                )

            if "error" in result:
                st.error(result["error"])
                st.session_state.chat_history.append(
                    {"role": "assistant", "content": f"Error: {result['error']}"}
                )
            else:
                parsed = result.get("parsed", {})
                if parsed.get("parse_error"):
                    st.warning("Could not parse structured JSON. Showing raw response.")
                    st.markdown(result["raw_response"])
                    st.session_state.chat_history.append(
                        {"role": "assistant", "content": result["raw_response"]}
                    )
                else:
                    _render_parsed_answer(parsed, result)

    elif user_input and not provider:
        st.error("Please configure an LLM provider in the sidebar.")

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2 — Agent Tasks
# ═══════════════════════════════════════════════════════════════════════════════
with tab_agent:
    st.header("Agent — Tactics Analysis")
    st.markdown(
        "Upload a project brief or paste text. The agent analyzes it against "
        "the AADT catalog and drafts a report you can review before saving."
    )

    input_method = st.radio("Input method", ["Paste text", "Upload file"], horizontal=True)

    agent_text = ""
    if input_method == "Paste text":
        agent_text = st.text_area("Project description / architecture brief", height=200)
    else:
        uploaded = st.file_uploader("Upload .md or .txt", type=["md", "txt"])
        if uploaded:
            agent_text = uploaded.read().decode("utf-8", errors="replace")
            st.text_area("Preview", agent_text, height=200, disabled=True)

    if st.button("Analyze", disabled=not agent_text or not provider):
        with st.spinner("Analyzing document against AADT catalog..."):
            result = run_query(
                user_query=agent_text,
                mode="agent_analyze",
                provider=provider,
                n_results=10,
            )

        if "error" in result:
            st.error(result["error"])
        else:
            parsed = result.get("parsed", {})
            if parsed.get("parse_error"):
                st.warning("Could not parse structured JSON.")
                st.text(result["raw_response"])
            else:
                st.session_state["agent_report"] = parsed
                st.session_state["agent_sources"] = result.get("retrieved_tactics", [])

                st.subheader("Draft Report")
                report_md = _build_report_markdown(parsed)
                st.markdown(report_md)

                with st.expander("Raw JSON"):
                    st.json(parsed)

    if "agent_report" in st.session_state:
        st.divider()
        report_name = st.text_input(
            "Report filename",
            value="tactics_analysis.md",
        )
        if st.button("Save report to /reports"):
            report_md = _build_report_markdown(st.session_state["agent_report"])
            out_path = REPORTS_DIR / report_name
            out_path.write_text(report_md, encoding="utf-8")
            st.success(f"Saved to {out_path}")

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 3 — Benchmark
# ═══════════════════════════════════════════════════════════════════════════════
with tab_benchmark:
    st.header("Benchmark — Model Comparison")
    st.markdown(
        "Run the benchmark question set across multiple models and compare "
        "groundedness, quality, hallucination, and latency."
    )

    bench_path = Path(__file__).resolve().parent.parent / "evaluation" / "benchmark_questions.json"
    if bench_path.exists():
        questions = json.loads(bench_path.read_text(encoding="utf-8"))
        st.info(f"Loaded {len(questions)} benchmark questions.")
    else:
        questions = []
        st.warning("No benchmark_questions.json found in /evaluation.")

    if providers:
        selected_models = st.multiselect(
            "Select models to benchmark",
            provider_names,
            default=provider_names[:2] if len(provider_names) >= 2 else provider_names,
        )
    else:
        selected_models = []

    max_questions = st.slider(
        "Questions to run",
        1,
        len(questions) if questions else 1,
        min(10, len(questions)) if questions else 1,
    )

    if st.button("Run Benchmark", disabled=not selected_models or not questions):
        progress = st.progress(0)
        results_table: list[dict] = []
        total = max_questions * len(selected_models)
        done = 0

        for q in questions[:max_questions]:
            for model_name in selected_models:
                prov = next(p for p in providers if p.name == model_name)
                bench_mode = q.get("type", "recommend")
                if bench_mode in ("adversarial", "ambiguous"):
                    bench_mode = "recommend"

                r = run_query(
                    user_query=q["question"],
                    mode=bench_mode,
                    provider=prov,
                    n_results=8,
                )

                parsed = r.get("parsed", {})
                from evaluation.score import compute_all_scores

                scores = compute_all_scores(
                    parsed=parsed,
                    retrieved=r.get("retrieved_tactics", []),
                    question_type=q.get("type", "recommend"),
                    latency=r.get("latency_seconds", 0),
                )
                results_table.append(
                    {
                        "question_id": q["id"],
                        "question_type": q.get("type", ""),
                        "difficulty": q.get("difficulty", ""),
                        "model": model_name,
                        **scores,
                        "error": r.get("error", ""),
                    }
                )
                done += 1
                progress.progress(done / total)

        st.session_state["bench_results"] = results_table
        st.success("Benchmark complete!")

    if "bench_results" in st.session_state:
        import pandas as pd
        import plotly.express as px

        df = pd.DataFrame(st.session_state["bench_results"])
        st.dataframe(df)

        if not df.empty:
            metric_cols = [
                "groundedness",
                "citation_presence",
                "parse_success",
                "dark_tactic_safety",
                "latency_seconds",
            ]
            available = [c for c in metric_cols if c in df.columns]
            summary = df.groupby("model")[available].mean().reset_index()

            st.subheader("Aggregate Scores by Model")
            st.dataframe(summary.style.format({c: "{:.3f}" for c in available}))

            for col in available:
                title = col.replace("_", " ").title()
                fig = px.bar(summary, x="model", y=col, title=f"Avg {title}")
                st.plotly_chart(fig, use_container_width=True)

            st.subheader("Scores by Question Type")
            if "question_type" in df.columns:
                by_type = df.groupby(["model", "question_type"])[available].mean().reset_index()
                st.dataframe(by_type)

            csv = df.to_csv(index=False)
            st.download_button("Download results CSV", csv, "benchmark_results.csv")
