"""Agent workflow: analyze documents and produce safe file actions."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from app.config import REPORTS_DIR, ProviderConfig
from rag.pipeline import run_query

logger = logging.getLogger(__name__)


def analyze_document(
    document_text: str,
    provider: ProviderConfig,
    n_results: int = 10,
) -> dict[str, Any]:
    """Run the agent analysis pipeline over user-provided text.

    Returns the structured analysis result from the LLM, including
    project_summary, awesome_tactics, dark_tactic_risks, recommendations.
    """
    result = run_query(
        user_query=document_text,
        mode="agent_analyze",
        provider=provider,
        n_results=n_results,
    )
    return result


def draft_report(analysis: dict[str, Any]) -> str:
    """Convert analysis output into a markdown report string."""
    parsed = analysis.get("parsed", {})
    if parsed.get("parse_error"):
        return f"# Analysis Report\n\n(Raw response — JSON parsing failed)\n\n{analysis.get('raw_response', '')}"

    lines = ["# Tactics Analysis Report", ""]

    lines.append("## Project Summary")
    lines.append(parsed.get("project_summary", "(no summary)"))
    lines.append("")

    lines.append("## Identified Tactics (Awesome)")
    for t in parsed.get("awesome_tactics", []):
        lines.append(
            f"- **{t.get('tactic_name', '')}** ({t.get('category', '')}): "
            f"{t.get('description', '')}"
        )
        if t.get("source"):
            lines.append(f"  - Source: {t['source']}")
        if t.get("source_doi"):
            lines.append(f"  - DOI: {t['source_doi']}")
    lines.append("")

    lines.append("## Identified Risks (Dark Tactics)")
    risks = parsed.get("dark_tactic_risks", [])
    for t in risks:
        if isinstance(t, dict):
            lines.append(
                f"- **{t.get('tactic_name', '')}** ({t.get('category', '')}): "
                f"{t.get('description', '')}"
            )
        else:
            lines.append(f"- {t}")
    lines.append("")

    lines.append("## Recommendations")
    for r in parsed.get("recommendations", []):
        lines.append(f"- {r}")
    lines.append("")

    lines.append("## Retrieved Sources")
    for src in analysis.get("retrieved_tactics", []):
        lines.append(
            f"- {src.get('title', '')} ({src.get('category', '')}, "
            f"{src.get('tactic_type', '')})"
        )
        if src.get("url"):
            lines.append(f"  - {src['url']}")
    lines.append("")

    lines.append(f"## Grounding")
    lines.append(parsed.get("grounding_note", ""))
    lines.append("")

    lines.append(f"*Model: {analysis.get('provider', '')} | "
                 f"Latency: {analysis.get('latency_seconds', 0):.1f}s*")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Agentic Tactics Copilot*")
    return "\n".join(lines)
